# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e657e7362cf60c970a3b005770b2a23a28b4b7075aeaa387772a29aab257f2ea895235547909e4919a55296c452eeaa920554478c137713be995dc482f3fa68e

test:
  secret_key_base: 1b3e6403bed6db39f1de6010ade7c398e8107791a23364f10c97da577eab9dea33b7fd1bc0a41f2314a891cded5008f25ecf03bcd50f5c8470eeec8ad125df05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
